# Generated by Django 5.2.7 on 2025-10-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_tradertransaction_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradertransaction",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="tradertransaction",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="tradertransaction",
            name="transaction_id",
        ),
    ]
