# Generated by Django 5.2.7 on 2025-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_useraccounttransaction_delete_tradertransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccounttransaction",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="transaction_files/"
            ),
        ),
        migrations.AddField(
            model_name="useraccounttransaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
