# Generated by Django 5.2.7 on 2025-12-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_trader"),
        ("transactions", "0007_useraccounttransaction_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccounttransaction",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="orders.order",
            ),
        ),
    ]
