# Generated by Django 5.2.7 on 2025-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_useraccounttransaction_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccounttransaction",
            name="is_rolled_back",
            field=models.BooleanField(default=False),
        ),
    ]
