# Generated by Django 5.2.7 on 2025-12-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_useraccounttransaction_is_rolled_back"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccounttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("withdraw", "withdraw"),
                    ("deposit", "deposit"),
                    ("expense", "expense"),
                ],
                max_length=10,
            ),
        ),
    ]
