# Generated by Django 5.2.7 on 2025-10-26 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_useraccount_created_useraccount_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_user_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
