# Generated by Django 5.2.7 on 2025-10-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_useraccount_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="created_by",
        ),
    ]
