# Generated by Django 5.2.7 on 2025-11-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_trader_options_alter_useraccount_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="last_name",
        ),
    ]
