# Generated by Django 5.2.7 on 2025-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("manager", "manager"),
                    ("admin", "admin"),
                    ("trader", "trader"),
                    ("driver", "driver"),
                ],
                default="admin",
                max_length=10,
            ),
        ),
    ]
