# Generated by Django 5.2.7 on 2025-11-20 15:31

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_driver_balance_alter_useraccount_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="driver",
            managers=[
                ("objects", users.models.UserAccountManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="trader",
            managers=[
                ("objects", users.models.UserAccountManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[
                ("objects", users.models.UserAccountManager()),
            ],
        ),
    ]
