# Generated by Django 5.2.7 on 2025-12-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_firebasedevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
        migrations.AlterModelOptions(
            name="trader",
            options={"verbose_name": "Trader", "verbose_name_plural": "Traders"},
        ),
    ]
