# Generated by Django 5.2.7 on 2026-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_driver_options_alter_trader_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
