# Generated by Django 5.2.7 on 2026-01-17 05:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_deliveryzone"),
        ("trader_pricing", "0001_initial"),
        ("users", "0016_alter_driver_options_alter_trader_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderdeliveryzone",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="يجب أن يكون السعر أكبر من أو يساوي 1"
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="traderdeliveryzone",
            unique_together={("delivery_zone", "trader")},
        ),
        migrations.AddConstraint(
            model_name="traderdeliveryzone",
            constraint=models.UniqueConstraint(
                fields=("delivery_zone", "trader"),
                name="unique_trader_delivery_zone",
                violation_error_message="هذا التاجر لديه بالفعل تسعيرة لهذه المنطقة",
            ),
        ),
    ]
