# Generated by Django 5.2.7 on 2025-10-26 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_alter_city_created_by_alter_city_updated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="city",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="city",
            name="transaction_id",
        ),
    ]
