# Generated by Django 5.2.7 on 2025-10-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_useraccount_updated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="created",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="updated_by",
        ),
    ]
