# Generated by Django 5.2.7 on 2025-10-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_useraccount_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="transaction_id",
        ),
    ]
