# Generated by Django 5.2.7 on 2025-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_zone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="extra_cost",
            new_name="extra_delivery_cost",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="subtotal",
            new_name="product_cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="order",
            name="reference_code",
            field=models.CharField(default="ref", max_length=15, unique=True),
        ),
    ]
