# Generated by Django 5.2.7 on 2025-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_extra_cost_order_extra_delivery_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference_code",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
