# Generated by Django 5.2.7 on 2025-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="latitude",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="longitude",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="product_payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                    ("remaining_fees", "Remaining Shipping Fees"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
    ]
