# Generated by Django 5.2.7 on 2025-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_customer_latitude_customer_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="longitude",
        ),
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                    ("remaining_fees", "Remaining Shipping Fees"),
                    ("cod", "Cash on Delivery"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
    ]
