# Generated by Django 5.2.7 on 2025-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_customer_latitude_remove_customer_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trader_merchant_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
