# Generated by Django 5.2.7 on 2025-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_trader_merchant_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="postpone_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
