# Generated by Django 5.2.7 on 2025-12-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_cancel_reason_order_postpone_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
