# Generated by Django 5.2.7 on 2025-12-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_latitude_alter_order_longitude"),
        ("users", "0014_alter_driver_managers_alter_trader_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="trader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.trader",
            ),
        ),
    ]
