# Generated by Django 5.2.7 on 2025-12-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_trader"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
    ]
