# Generated by Django 5.2.7 on 2025-12-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_remove_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
