# Generated by Django 5.2.7 on 2025-12-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_order_latitude_alter_order_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
