# Generated by Django 5.2.7 on 2025-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_order_delivery_cost_alter_order_product_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="postpone_count",
            field=models.IntegerField(default=0),
        ),
    ]
