# Generated by Django 5.2.7 on 2026-01-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_postpone_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_return",
            field=models.BooleanField(default=False, verbose_name="Is Return Order"),
        ),
    ]
