# Generated by Django 5.2.7 on 2026-01-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_order_is_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trader_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
