# Generated by Django 5.2.7 on 2026-01-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_order_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_changed_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
